services:
  app:
    build: .
    ports:
      - "3007:3007"  
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb  
    restart: always  

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
