version: '3.8'

services:
  task-service:
    build: .
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
