version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://db:27017/project-management
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: